// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://huzwhcmcdvakcwjdpaps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1endoY21jZHZha2N3amRwYXBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3ODQ4MDEsImV4cCI6MjA3MzM2MDgwMX0.iBd8l-nRhSv7jCTvrEmffyM6dKm6iEffv3qM7A9PyBg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});